name: pdfjimmy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: any
  syncfusion_flutter_pdfviewer: ^27.1.48
  syncfusion_flutter_pdf: ^27.1.48
  path_provider: any
  file_picker: any
  animated_text_kit: any
  google_fonts: ^6.3.2
  animated_splash_screen: any
  flutter_colorpicker: any
  shared_preferences: any
  flutter_speed_dial: any
  flutter_svg: any
  intl: any
  translator: ^1.0.4+1
  image_picker: any
  speech_to_text: ^7.1.0
  flutter_tts: any
  get_storage: any
  http: any
  sqflite: any
  provider: ^6.1.5
  share_plus: any
  url_launcher: any
  permission_handler: ^12.0.1
  path: any
  signature: ^5.4.0
  crypto: ^3.0.3
  uuid: any
  crop_your_image: ^1.0.2
  image: ^4.0.0
  video_player: ^2.8.6
  printing: ^5.13.4
  pdf: ^3.11.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  google_mlkit_document_scanner: ^0.2.0
  google_mlkit_text_recognition: ^0.13.0
  gap: ^3.0.1
  flutter_secure_storage: ^10.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  sqflite_common_ffi: ^2.3.6
  camera: ^0.11.2+1
  cunning_document_scanner: ^1.2.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pdfjimmy.png
    - assets/splash.mp4

flutter_icons:
  image_path: icons/playstore.png
  android: true
  ios: true
  macos: true
  web: true
  linux: true
  windows: true
  generate: true
